import type { ShipmentDetailViewModel, ShipmentLabel } from './view-model';

/** Artificial component fixtures. Never import into operational data or API code. */
const labels = {
  preparing: { label: 'قيد التجهيز', tone: 'neutral' },
  onRoad: { label: 'في الطريق', tone: 'info' },
  arrived: { label: 'وصلت للمدينة', tone: 'warning' },
  delivered: { label: 'تم التسليم', tone: 'success' },
  paid: { label: 'مدفوع', tone: 'success' },
  unpaid: { label: 'غير مدفوع', tone: 'neutral' },
} satisfies Record<string, ShipmentLabel>;

export const shipmentFixtures: ShipmentDetailViewModel[] = [
  {
    id: 'sample-001',
    tracking: 'DEMO-2048',
    sender: 'أحمد المثال',
    recipient: 'سارة النموذج',
    origin: 'طرابلس',
    destination: 'بنغازي',
    type: 'طرد',
    size: 'متوسط',
    status: labels.onRoad,
    payment: labels.paid,
    driver: 'علي المثال',
    trip: 'DEMO-T12',
    price: '—',
    createdLabel: '١٣ سبتمبر، ١٠:٤٠',
    createdDate: '2026-09-13',
    senderPhone: '09X XXX XXXX',
    recipientPhone: '09X XXX XXXX',
    recipientAddress: 'عنوان توضيحي — بنغازي',
    originBranch: 'فرع توضيحي — طرابلس',
    destinationBranch: 'فرع توضيحي — بنغازي',
    deliveryMethod: 'توصيل إلى العنوان',
    notes: 'مثال توضيحي لموضع ملاحظات الشحنة. هذه البيانات لا تمثل طلبًا فعليًا.',
    timeline: [
      {
        id: 'event-1',
        label: 'في الطريق',
        timestamp: '١٣ سبتمبر، ١٢:٣٠',
        note: 'نص توضيحي لآخر تحديث.',
      },
      { id: 'event-2', label: 'قيد التجهيز', timestamp: '١٣ سبتمبر، ١٠:٤٠' },
    ],
  },
  {
    id: 'sample-002',
    tracking: 'DEMO-2047',
    sender: 'مريم المثال',
    recipient: 'يوسف النموذج',
    origin: 'طرابلس',
    destination: 'مصراتة',
    type: 'مستندات',
    size: 'صغير',
    status: labels.preparing,
    payment: labels.unpaid,
    driver: '—',
    trip: '—',
    price: '—',
    createdLabel: '١٣ سبتمبر، ١٠:٢٥',
    createdDate: '2026-09-13',
    senderPhone: '09X XXX XXXX',
    recipientPhone: '09X XXX XXXX',
    recipientAddress: 'عنوان توضيحي — مصراتة',
    originBranch: 'فرع توضيحي — طرابلس',
    destinationBranch: 'فرع توضيحي — مصراتة',
    deliveryMethod: 'استلام من الفرع',
    notes: 'لا توجد ملاحظات في هذا المثال.',
    timeline: [{ id: 'event-1', label: 'قيد التجهيز', timestamp: '١٣ سبتمبر، ١٠:٢٥' }],
  },
  {
    id: 'sample-003',
    tracking: 'DEMO-2046',
    sender: 'خالد المثال',
    recipient: 'هند النموذج',
    origin: 'بنغازي',
    destination: 'طرابلس',
    type: 'طرد',
    size: 'كبير',
    status: labels.arrived,
    payment: labels.paid,
    driver: 'سالم المثال',
    trip: 'DEMO-T11',
    price: '—',
    createdLabel: '١٣ سبتمبر، ٠٩:٥٠',
    createdDate: '2026-09-13',
    senderPhone: '09X XXX XXXX',
    recipientPhone: '09X XXX XXXX',
    recipientAddress: 'عنوان توضيحي — طرابلس',
    originBranch: 'فرع توضيحي — بنغازي',
    destinationBranch: 'فرع توضيحي — طرابلس',
    deliveryMethod: 'استلام من الفرع',
    notes: 'لا توجد ملاحظات في هذا المثال.',
    timeline: [{ id: 'event-1', label: 'وصلت للمدينة', timestamp: '١٣ سبتمبر، ١٦:٠٠' }],
  },
  {
    id: 'sample-004',
    tracking: 'DEMO-2045',
    sender: 'نور المثال',
    recipient: 'عمر النموذج',
    origin: 'مصراتة',
    destination: 'سبها',
    type: 'طرد',
    size: 'متوسط',
    status: labels.onRoad,
    payment: labels.unpaid,
    driver: 'علي المثال',
    trip: 'DEMO-T10',
    price: '—',
    createdLabel: '١٣ سبتمبر، ٠٩:١٥',
    createdDate: '2026-09-13',
    senderPhone: '09X XXX XXXX',
    recipientPhone: '09X XXX XXXX',
    recipientAddress: 'عنوان توضيحي — سبها',
    originBranch: 'فرع توضيحي — مصراتة',
    destinationBranch: 'فرع توضيحي — سبها',
    deliveryMethod: 'توصيل إلى العنوان',
    notes: 'لا توجد ملاحظات في هذا المثال.',
    timeline: [{ id: 'event-1', label: 'في الطريق', timestamp: '١٣ سبتمبر، ١٣:٠٠' }],
  },
  {
    id: 'sample-005',
    tracking: 'DEMO-2044',
    sender: 'طارق المثال',
    recipient: 'ليلى النموذج',
    origin: 'طرابلس',
    destination: 'الزاوية',
    type: 'مستندات',
    size: 'صغير',
    status: labels.delivered,
    payment: labels.paid,
    driver: 'سالم المثال',
    trip: 'DEMO-T09',
    price: '—',
    createdLabel: '١٢ سبتمبر، ١٥:٣٠',
    createdDate: '2026-09-12',
    senderPhone: '09X XXX XXXX',
    recipientPhone: '09X XXX XXXX',
    recipientAddress: 'عنوان توضيحي — الزاوية',
    originBranch: 'فرع توضيحي — طرابلس',
    destinationBranch: 'فرع توضيحي — الزاوية',
    deliveryMethod: 'توصيل إلى العنوان',
    notes: 'لا توجد ملاحظات في هذا المثال.',
    timeline: [{ id: 'event-1', label: 'تم التسليم', timestamp: '١٣ سبتمبر، ٠٩:١٠' }],
  },
  {
    id: 'sample-006',
    tracking: 'DEMO-2043',
    sender: 'هدى المثال',
    recipient: 'أنس النموذج',
    origin: 'سبها',
    destination: 'طرابلس',
    type: 'طرد',
    size: 'كبير',
    status: labels.preparing,
    payment: labels.unpaid,
    driver: '—',
    trip: '—',
    price: '—',
    createdLabel: '١٢ سبتمبر، ١٤:١٠',
    createdDate: '2026-09-12',
    senderPhone: '09X XXX XXXX',
    recipientPhone: '09X XXX XXXX',
    recipientAddress: 'عنوان توضيحي — طرابلس',
    originBranch: 'فرع توضيحي — سبها',
    destinationBranch: 'فرع توضيحي — طرابلس',
    deliveryMethod: 'استلام من الفرع',
    notes: 'لا توجد ملاحظات في هذا المثال.',
    timeline: [{ id: 'event-1', label: 'قيد التجهيز', timestamp: '١٢ سبتمبر، ١٤:١٠' }],
  },
  {
    id: 'sample-007',
    tracking: 'DEMO-2042',
    sender: 'زياد المثال',
    recipient: 'ريم النموذج',
    origin: 'بنغازي',
    destination: 'مصراتة',
    type: 'طرد',
    size: 'متوسط',
    status: labels.delivered,
    payment: labels.paid,
    driver: 'سالم المثال',
    trip: 'DEMO-T08',
    price: '—',
    createdLabel: '١٢ سبتمبر، ١٢:٢٠',
    createdDate: '2026-09-12',
    senderPhone: '09X XXX XXXX',
    recipientPhone: '09X XXX XXXX',
    recipientAddress: 'عنوان توضيحي — مصراتة',
    originBranch: 'فرع توضيحي — بنغازي',
    destinationBranch: 'فرع توضيحي — مصراتة',
    deliveryMethod: 'استلام من الفرع',
    notes: 'لا توجد ملاحظات في هذا المثال.',
    timeline: [{ id: 'event-1', label: 'تم التسليم', timestamp: '١٣ سبتمبر، ١٠:٠٠' }],
  },
  {
    id: 'sample-008',
    tracking: 'DEMO-2041',
    sender: 'رنا المثال',
    recipient: 'كريم النموذج',
    origin: 'مصراتة',
    destination: 'بنغازي',
    type: 'مستندات',
    size: 'صغير',
    status: labels.arrived,
    payment: labels.paid,
    driver: 'علي المثال',
    trip: 'DEMO-T07',
    price: '—',
    createdLabel: '١١ سبتمبر، ١١:٣٠',
    createdDate: '2026-09-11',
    senderPhone: '09X XXX XXXX',
    recipientPhone: '09X XXX XXXX',
    recipientAddress: 'عنوان توضيحي — بنغازي',
    originBranch: 'فرع توضيحي — مصراتة',
    destinationBranch: 'فرع توضيحي — بنغازي',
    deliveryMethod: 'استلام من الفرع',
    notes: 'لا توجد ملاحظات في هذا المثال.',
    timeline: [{ id: 'event-1', label: 'وصلت للمدينة', timestamp: '١٢ سبتمبر، ١٩:٠٠' }],
  },
];
