export const moduleShells = {
  shipments: {
    title: 'الشحنات',
    description: 'إدارة الشحنات ومتابعة كل خطوة من الاستلام إلى التسليم.',
    entity: 'شحنة',
    action: 'إضافة شحنة',
    columns: ['رقم التتبع', 'المرسل', 'المستلم', 'المسار', 'الحالة', 'الدفع'],
    phase: 'C',
  },
  trips: {
    title: 'الرحلات',
    description: 'تنظيم الرحلات ومسارات النقل بين المدن.',
    entity: 'رحلة',
    action: 'إنشاء رحلة',
    columns: ['الرحلة', 'من', 'إلى', 'السائق', 'المغادرة', 'الحالة', 'الشحنات'],
    phase: 'D',
  },
  drivers: {
    title: 'السائقون',
    description: 'فريق التوصيل، فروعه، وأعماله الجارية.',
    entity: 'سائق',
    action: 'إضافة سائق',
    columns: ['الاسم', 'الهاتف', 'الفرع', 'الحالة التشغيلية', 'العمل الحالي'],
    phase: 'D',
  },
  cities: {
    title: 'المدن',
    description: 'المدن التي تربط بينها شبكة Porta Delivery.',
    entity: 'مدينة',
    action: 'إضافة مدينة',
    columns: ['المدينة', 'الاسم بالإنجليزية', 'الرمز', 'ترتيب العرض', 'الحالة'],
    phase: 'E',
  },
  branches: {
    title: 'الفروع',
    description: 'نقاط الاستلام والتسليم وبيانات التواصل.',
    entity: 'فرع',
    action: 'إضافة فرع',
    columns: ['الفرع', 'المدينة', 'العنوان', 'الهاتف', 'الحالة'],
    phase: 'E',
  },
  'shipment-types': {
    title: 'أنواع الشحنات',
    description: 'تصنيفات واضحة لتنظيم الشحنات.',
    entity: 'نوع شحنة',
    action: 'إضافة نوع',
    columns: ['النوع', 'الاسم بالإنجليزية', 'الرمز', 'الحالة'],
    phase: 'E',
  },
  pricing: {
    title: 'التسعير',
    description: 'تسعيرات المسارات والأنواع وفترات السريان.',
    entity: 'تسعيرة',
    action: 'إضافة تسعيرة',
    columns: ['المسار', 'النوع والحجم', 'السعر الأساسي', 'رسوم التوصيل', 'فترة السريان', 'الحالة'],
    phase: 'E',
  },
  payments: {
    title: 'المدفوعات',
    description: 'حالات الدفع والتحصيل والاسترجاع، مستقلة عن حالة الشحنة.',
    entity: 'دفعة',
    action: null,
    columns: ['الشحنة', 'طريقة الدفع', 'حالة الدفع', 'المحصّل', 'المسترجع', 'الصافي'],
    phase: 'F',
  },
  reports: {
    title: 'التقارير',
    description: 'قراءة أداء التشغيل والإيرادات عبر الفترات والمسارات.',
    entity: 'تقرير',
    action: null,
    columns: ['الفترة', 'المسار', 'حجم الشحنات', 'حالات التسليم', 'الإيرادات'],
    phase: 'F',
  },
  users: {
    title: 'المستخدمون والصلاحيات',
    description: 'إدارة الوصول إلى مساحة العمل حسب المهام والمسؤوليات.',
    entity: 'مستخدم',
    action: 'إضافة مستخدم',
    columns: ['الاسم', 'البريد الإلكتروني', 'الدور', 'الفرع', 'الحالة'],
    phase: 'G',
  },
  audit: {
    title: 'سجل العمليات',
    description: 'سجل منظم للنشاط والتغييرات المسموح بعرضها.',
    entity: 'عملية',
    action: null,
    columns: ['الوقت', 'المستخدم', 'الإجراء', 'العنصر', 'الملخص'],
    phase: 'G',
  },
} as const;
export type ShellModule = keyof typeof moduleShells;
export function isShellModule(value: string): value is ShellModule {
  return Object.hasOwn(moduleShells, value);
}
